name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks out the code
    - name: Checkout the code
      uses: actions/checkout@v1

    # Installs dependencies
    - name: Install dependencies
      run: npm install

    # Builds the project
    - name: Run build
      run: npm run build

    # Deploys the code
    - name: Deploy build to AWS S3
      uses: docker://amazon/aws-cli:2.0.7
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 cp --recursive ./build s3://tagocore-docs/docs

    # Deploys the code
    - name: Invalidate Cloudfront
      uses: docker://amazon/aws-cli:2.0.7
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: cloudfront create-invalidation --distribution-id E3F3MDT9Y9H6I0 --paths "/docs" "/docs/*"
